import { a } from "maath/dist/objectSpread2-284232a6.esm";
import {
  mobile,
  backend,
  creator,
  web,
  javascript,
  typescript,
  html,
  css,
  reactjs,
  redux,
  tailwind,
  nodejs,
  mongodb,
  git,
  figma,
  bootstrap,
  firebase,
  next,
  web3,
  docker,
  tapout,
  yiess,
  lens,
  gastos,
  todo,
  cafe,
  blog,
  startup,
  portfolio,
  bootstrapProject,
  threejs,
} from "../assets";

export const navLinks = [
  {
    id: "about",
    title: "About",
  },
  {
    id: "techs",
    title: "My Stack",
  },
  {
    id: "work",
    title: "Work",
  },
  {
    id: "contact",
    title: "Contact",
  },
];

const services = [
  {
    title: "Web Developer",
    icon: web,
  },
  {
    title: "Problem Solver",
    icon: mobile,
  },
  {
    title: "Fast learner",
    icon: backend,
  },
  {
    title: "Adaptable to changes",
    icon: creator,
  },
];

const technologies = [
  {
    name: "html 5",
    icon: html,
  },
  {
    name: "CSS 3",
    icon: css,
  },
  {
    name: "JavaScript",
    icon: javascript,
  },
  {
    name: "TypeScript",
    icon: typescript,
  },
  {
    name: "React JS",
    icon: reactjs,
  },
  {
    name: "Next JS",
    icon: next,
  },
  {
    name: "Redux Toolkit",
    icon: redux,
  },
  {
    name: "Tailwind CSS",
    icon: tailwind,
  },
  // {
  //   name: "Bootstrap",
  //   icon: bootstrap,
  // },
  {
    name: "Node JS",
    icon: nodejs,
  },
  // {
  //   name: "MongoDB",
  //   icon: mongodb,
  // },
  // {
  //   name: "Three JS",
  //   icon: threejs,
  // },
  {
    name: "Firebase",
    icon: firebase,
  },
  {
    name: "Git",
    icon: git,
  },
  {
    name: "Figma",
    icon: figma,
  },
  // {
  //   name: "docker",
  //   icon: docker,
  // },
];

const experiences = [
  {
    title: "Front-end Developer",
    company_name: "Tapout Perú",
    icon: tapout,
    iconBg: "#000",
    date: "March 2021 - April 2021",
    points: [
      "Make a new home page following a PSD file to make a UI with a pixel-perfect fit",
      "Use WordPess and the page builder WPBakery to construct the interface",
      "Implementing responsive design and ensuring cross-browser compatibility.",
    ],
  },
  {
    title: "Front-end/Blockchain developer",
    company_name: "Yiess",
    icon: yiess,
    iconBg: "#fff",
    date: "September 2021 - March 2023",
    points: [
      "In charge of the creation of front-end components, as well as in the refactoring of the code",
      "Assisting with the NFTs minting page as well as the purchasing system for sell the images using metaplex and the Candy Machine Contract.",
      "Review and perform functions to connect to the project's smart contract",
      "Create new functionalities for the project, like allow the users to create NFTs, give like to them, and to sell them",
      "Developing and maintaining the web applications of the project using React.js/Next.js, Javascript/Typescript and other related technologies.",
      "Collaborating with cross-functional teams and other developers to create a good product.",
      "Implementing responsive design and ensuring cross-browser compatibility.",
    ],
  },
];

// const experiencesOld = [
//   {
//     title: "Front-end Developer",
//     company_name: "Tapout Perú",
//     icon: tapout,
//     iconBg: "#000",
//     date: "March 2020 - April 2021",
//     points: [
//       "Developing and maintaining web applications using React.js and other related technologies.",
//       "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
//       "Implementing responsive design and ensuring cross-browser compatibility.",
//       "Participating in code reviews and providing constructive feedback to other developers.",
//     ],
//   }
// ];

const testimonials = [
  {
    testimonial:
      "I thought it was impossible to make a website as beautiful as our product, but Rick proved me wrong.",
    name: "Sara Lee",
    designation: "CFO",
    company: "Acme Co",
    image: "https://randomuser.me/api/portraits/women/4.jpg",
  },
  {
    testimonial:
      "I've never met a web developer who truly cares about their clients' success like Rick does.",
    name: "Chris Brown",
    designation: "COO",
    company: "DEF Corp",
    image: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    testimonial:
      "After Rick optimized our website, our traffic increased by 50%. We can't thank them enough!",
    name: "Lisa Wang",
    designation: "CTO",
    company: "456 Enterprises",
    image: "https://randomuser.me/api/portraits/women/6.jpg",
  },
];

const projects = [
  {
    name: "A social network for AI images",
    description: `I cloned three views of the page: www.artofficialintelligence.xyz/gallery. A social network that allow users to create and share images generated by an AI. I developed the front-end and used the Lens Protocol API to retrieve the necessary information.`,
    tags: [
      {
        name: "next",
        color: "text-white",
      },
      {
        name: "ant-desing",
        color: "blue-text-gradient",
      },
      {
        name: "GraphQL",
        color: "pink-text-gradient",
      },
    ],
    image: lens,
    source_code_link: "https://github.com/HereFrank/Next-challenge",
    project_link: "https://next-challenge-zeta.vercel.app/",
  },
  {
    name: "Expense management application",
    description:
      "This is a web application that enables users to manage their expenses. Users can categorize their expenses and see where their money is being spent.",
    tags: [
      {
        name: "react",
        color: "blue-text-gradient",
      },
      {
        name: "scss",
        color: "pink-text-gradient",
      },
      {
        name: "firebase",
        color: "orange-text-gradient",
      },
    ],
    image: gastos,
    source_code_link: "https://github.com/HereFrank/expenseManager",
    project_link: "https://app-lista-gastos-cc4bf.web.app/",
  },
  {
    name: "Todo App",
    description:
      "This React app allows users to manage their daily tasks. Users can create, read, edit, and delete tasks as needed.",
    tags: [
      {
        name: "react",
        color: "blue-text-gradient",
      },
      {
        name: "css",
        color: "blue-text-gradient",
      },
      {
        name: "localStorage",
        color: "green-text-gradient",
      },
    ],
    image: todo,
    source_code_link: "https://github.com/HereFrank/todoApp",
    project_link: "https://app-lista-tareas-c9bc9.web.app/",
  },
  {
    name: "Restaurant website",
    description: "A home page of a restaurant website",
    tags: [
      {
        name: "html",
        color: "orange-text-gradient",
      },
      {
        name: "css",
        color: "blue-text-gradient",
      },
      {
        name: "javascript",
        color: "text-yellow-500",
      },
    ],
    image: cafe,
    source_code_link: "https://github.com/HereFrank/Restaurant",
    project_link: "https://herefrank.github.io/Restaurant/",
  },
  {
    name: "Blog website",
    description: "A home page of a blog website",
    tags: [
      {
        name: "html",
        color: "orange-text-gradient",
      },
      {
        name: "css",
        color: "blue-text-gradient",
      },
    ],
    image: blog,
    source_code_link: "https://github.com/HereFrank/blog",
    project_link: "https://herefrank.github.io/blog/",
  },
  {
    name: "Startup website",
    description: "A home page of a startup website",
    tags: [
      {
        name: "html",
        color: "orange-text-gradient",
      },
      {
        name: "css",
        color: "blue-text-gradient",
      },
    ],
    image: startup,
    source_code_link: "https://github.com/HereFrank/startup",
    project_link: "https://herefrank.github.io/startup/",
  },
  {
    name: "Portfolio website",
    description: "A portfolio website",
    tags: [
      {
        name: "html",
        color: "orange-text-gradient",
      },
      {
        name: "css",
        color: "blue-text-gradient",
      },
    ],
    image: portfolio,
    source_code_link: "https://github.com/HereFrank/my-projects",
    project_link: "https://herefrank.github.io/my-projects/",
  },
  {
    name: "Bootstrap website",
    description: "A website page made with Bootstrap",
    tags: [
      {
        name: "html",
        color: "orange-text-gradient",
      },
      {
        name: "bootstrap",
        color: "text-purple-700",
      },
    ],
    image: bootstrapProject,
    source_code_link: "https://github.com/HereFrank/Bootstrap4",
    project_link: "https://herefrank.github.io/Bootstrap4/",
  },
];

export { services, technologies, experiences, testimonials, projects };
